# Generated by Django 5.2.8 on 2025-11-19 22:59

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('source_type', models.CharField(choices=[('S', 'site'), ('B', 'book'), ('Y', 'YouTube channel'), ('N', 'no source')], default='N', max_length=2)),
                ('url', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thai_title', models.CharField(blank=True, max_length=200, null=True)),
                ('thai_transcript_name', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_recipes', models.IntegerField(default=0)),
                ('number_of_veg_recipes', models.IntegerField(default=0)),
                ('number_of_fish_recipes', models.IntegerField(default=0)),
                ('number_of_seafood_recipes', models.IntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.ingredienttype'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('subsource', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=400)),
                ('vegetarian', models.CharField(choices=[('V', 'vegetarian'), ('F', 'with fish'), ('S', 'with seafood'), ('M', 'with meat'), ('?', 'no info')], default='?', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.category')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.source')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAlternatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional', models.BooleanField(default=False)),
                ('ingredients', models.ManyToManyField(to='tree.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipe_photos/')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='suggested', max_length=20)),
                ('is_restaurant_dish', models.BooleanField(default=False, verbose_name='Restaurant dish photo')),
                ('is_handmade', models.BooleanField(default=False, verbose_name='Handmade photo')),
                ('is_ingredients_process', models.BooleanField(default=False, verbose_name='Ingredients/cooking process photo')),
                ('is_main_photo', models.BooleanField(default=False, verbose_name='Main photo')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tree.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='UserRecipeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooked', models.CharField(choices=[('N', 'Never cooked'), ('W', 'Want to cook'), ('C', 'Cooked'), ('S', 'My signature dish')], default='N', max_length=1)),
                ('tasted', models.CharField(choices=[('N', 'Never tasted'), ('W', 'Want to taste'), ('T', 'Tasted'), ('F', 'My favorite dish')], default='N', max_length=1)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='users',
            field=models.ManyToManyField(through='tree.UserRecipeRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
